### ISSUE TITLE
テーブル設計

### ISSUE THREAD

**Issue by kimuray** [kimuray/nomini_reserve#1]
現状ある情報でテーブル設計を行う。
テーブル設計完了後railsでモデルを作成する。

 ## 完了条件
- [x] テーブル設計の大枠を作成する
  * ひとまずスプレットシートにテーブル定義書く
  * 余力あればER図作る？
- [x] テーブル設計のレビュー
- [x] レビュー完了後、モデルを作成する

**Comment by stobita** [comment]
# 作成ver0.1
新規作成
詳細はdevelopmentチャンネルのPurpose参照
## 補足
* ユーザーのポイントは履歴管理の可能性を検討した上で別テーブルで管理。Userテーブルに統合することも検討
* アンケートのリレーションについてはより適切な設計があればご指摘ください
* 課金管理についてはAPI仕様によって変動
* ケアレスミス、不足項目を発見した際には適宜修正お願い致します

**Comment by kimuray** [comment]
早速作成いただきありがとうございます！
以下レビューです！

* Userテーブル
  * Facebook認証を考えるのであればproviderとuidカラムがあるべきかも
  * ポイントはUserテーブルで管理したほうが良さそう
    * ポイント履歴の可能性を考えてもuser_idで履歴管理すれば行けそうな気がするので

* shopテーブル
  * service_timeは開店時間~閉店時間のイメージ？もしくはコースの時間(2時間とか)？
    * 前者なら開店時間、閉店時間でカラム分けたほうが良さそう
    * 後者であればtimeでなくfloatとかでもいいかも
  * imageはbinaryを埋め込むよりS3などの外部ストレージに画像を保存してそのパスを保存する形の方がいいと思う(つまりstring型がよいかと)

* reservationテーブル
  * 誰が予約したか(user_id)を入れなくてよい？
  * カラム名が抽象的なものをもう少し具体的にしても良さそう
    * date → use_date
    * time → use_time
    * people → people_count

* pointテーブル
  * 個人的にはusersテーブル統合でもよいかな？と思ったり

* questionnaireテーブル
  * 該当の項目が何で答えてほしい(string, integer, boolean)のかを保持するカラムが必要かも

* questionnaire_answerテーブル
  * booleanはboolean_valueにするべきと思う(booleanは予約語なんじゃないかという予感)
    * RubyやRailsのメソッドにありそうな名前は避けるのがベターかも

個人的な感覚ですがreservationとquestionnaireの間にテーブルがあってもいいような気がしてます！
後からアンケートの取りまとめなどが発生した際に予約情報から取りまとめるよりアンケートの役割を持ったモデルがあった方が良いかもって感じです！
以下みたいな感じで

![untitled 7](https://user-images.githubusercontent.com/14311071/29747350-52929204-8b33-11e7-8c2c-e3178e63319d.png)

ざっとみてみた感じのコメントは以上になります！
作りながら設計見直すとかは出てくるかもしれませんが大枠は大丈夫かなと思いました！

**Comment by kimuray** [comment]
アンケートのところでいうと、セレクトボックスで選択させるような場合もあると考えるとquestionnaireに1対多で選択仕様のテーブルが必要になるかもしれないなあと、ふと思いました！

**Comment by stobita** [comment]
ご確認いただき、ありがとうございます！
ご指摘いただいた内容の取り込み完了しました。ただ、アンケート部分については指摘内容を理解仕切れていないかもしれませんので、再度ご確認いただければと思います。一応自分の想定ではquestionnaire_answerがアンケート集計用モデルなイメージで作ってました。

**Comment by stobita** [comment]
セレクトボックスについてですが、確かに考慮から抜けておりました。ただ現運用で使っていない場合、テーブル追加して、ロジック増やすとなると工数が増えそうなイメージなので、場合によっては後付の方がいいような気もします。そう考えるとbooleanの回答項目も余分になってしまう感もありますが・・・

**Comment by kimuray** [comment]
> ただ、アンケート部分については指摘内容を理解仕切れていないかもしれませんので、再度ご確認いただければと思います。一応自分の想定ではquestionnaire_answerがアンケート集計用モデルなイメージで作ってました

イメージ的には
指摘でいったenqureteがアンケート本体(アンケート用紙的なイメージ)
questionnaireがアンケートの項目
questionnaire_answerがアンケート一つに対する各項目の回答

って感じです！（わかりづらいかも…)
questionnaire_answerがむしろ中間テーブルになるようなイメージですかね
シートの色を変えてアンケート周りを記載してみました！

reservationに複数のアンケート回答が紐づいていると予約情報の中でアンケート周りの操作が必要になりそうなので微妙に役割が違うような気がしたって感じです！
enqueteというアンケートを管理するモデルをおくことでreservationはアンケートがあるってことだけを意識すればよくなるので実装が進んだ時に柔軟にアンケート周りを対応できるようになるのではないかなあって感じです！

**Comment by stobita** [comment]
なるほど！いただいたご説明でスッキリしました。仰るとおりの実装がふさわしいですね。
理解ついでにアンケート周りのテーブル名統一しました。気になるところありましたら、ご指摘ください。

**Comment by kimuray** [comment]
一旦大丈夫だと思います！実装進めていってうまくいかないところなどあれば都度修正していく感じで行きましょう！

あとは定義したテーブルとモデルをざくっと作ってpull requestください！

**Comment by stobita** [comment]
Userテーブルにメール認証用のカラム(devise準拠)を追加しました。
ロック機能用カラムについては保留としています。
